package basis.opgaven;

import basis.opgaven.domein.Afdeling;
import basis.opgaven.domein.Cursist;
import basis.opgaven.domein.Cursus;
import basis.opgaven.domein.School;
import basis.opgaven.domein.SchoolParser;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


public class _CursusApplic extends javax.swing.JFrame {

    private DefaultListModel<Cursist> modelCursisten;
    
    public _CursusApplic() {
        initComponents();
        modelCursisten = new DefaultListModel();
        lstCursisten.setModel(modelCursisten);
        
        
                   
//        Cursist c = new Cursist("Jan");
//        modelCursisten.addElement(c);
        
        SchoolParser sp = new SchoolParser("src/basis/opgaven/domein/school.json");
        Cursus cursus = sp.haalCursusOp();
        School sch = sp.haalInfoOp();
        ArrayList cursisten = cursus.getCursisten();
        ArrayList afd = sch.getAfdelingen();
        modelCursisten.addAll(cursisten);
        School school = sch.getSchool();
        String naam = school.getNaam();
        String provincie = school.getProvincie();
        String website = school.getWebsite();
                             
        lblCursus.setText("Nieuwe Inschrijving : "+ cursus.getNaam());
        lblAfdeling.setText(afd.toString());
       lblSchool.setText(naam + " in " + provincie +  " meer info op " + website);
        
        
//        String naam = school.getNaam();
//        String provincie = school.getNaam();
//        String website = school.getNaam();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursisten = new javax.swing.JList<>();
        lblCursus = new javax.swing.JLabel();
        lblAfdeling = new javax.swing.JLabel();
        lblSchool = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingeschreven cursisten"));

        jScrollPane1.setViewportView(lstCursisten);

        lblCursus.setText("Hier komt de omchrijving van de cursus");

        lblAfdeling.setText("Hier komt de afdeling");

        lblSchool.setText("Informatie school");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(lblCursus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAfdeling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSchool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblSchool)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAfdeling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCursus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         
       
                
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_CursusApplic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_CursusApplic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_CursusApplic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_CursusApplic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _CursusApplic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAfdeling;
    private javax.swing.JLabel lblCursus;
    private javax.swing.JLabel lblSchool;
    private javax.swing.JList<Cursist> lstCursisten;
    // End of variables declaration//GEN-END:variables
}
