package basis.opgaven;

import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStream;
import static java.time.Clock.system;
import java.util.Properties;
import javax.swing.JOptionPane;

public class _PuntenBijhouden extends javax.swing.JFrame {

    private final String locatiePuntenBestand = _PuntenBijhouden.class.getResource("").getPath()+"punten.properties";
    private Properties puntenStand;
    private final String sourceBestand="C:/Users/alima/OneDrive/Documents/NetBeansProjects/2021-03-03_MaesAli_Properties/src/basis/opgaven/punten.properties";
    public _PuntenBijhouden() {
        System.out.println(locatiePuntenBestand);
        /**
         * lees het bestand met punten in in een klasse Properties Het Project
         * moet je zeker BUILDEN, anders kan je geen getResourceAsStream
         * gebruiken
         */
            puntenStand = new Properties();
//        try(InputStream input = _PuntenBijhouden.class.getResourceAsStream("/basis/opgaven/punten.properties")) 
        try(FileReader input = new FileReader(sourceBestand)){
            puntenStand.load(input);
            puntenStand.list(System.out);
            
        } catch (Exception ex) {
            System.out.println("Inladen punten faalt voor locatie: " + locatiePuntenBestand);
            ex.printStackTrace(System.err);
            // laat eventueel een popup verschijnen met een foutbericht
            JOptionPane.showMessageDialog(this,"Fout tijdens lezen van puntenbestand");
            return;
        }
        initComponents();
        setLocationRelativeTo(null);
        String puntPiet = puntenStand.getProperty("Piet");
        fxtPiet.setValue(Integer.parseInt(puntPiet));
        // beter onder gebruiken dan bovenste manier
        fxtEllen.setValue(Integer.parseInt(puntenStand.getProperty("Ellen")));
        fxtJan.setValue(Integer.parseInt(puntenStand.getProperty("Jan")));
        fxtKaren.setValue(Integer.parseInt(puntenStand.getProperty("Karen")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fxtJan = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        fxtPiet = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        fxtKaren = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        fxtEllen = new javax.swing.JFormattedTextField();
        btnOpslaan = new javax.swing.JButton();
        fxtJan1 = new javax.swing.JFormattedTextField();
        fxtPiet1 = new javax.swing.JFormattedTextField();
        fxtKaren1 = new javax.swing.JFormattedTextField();
        fxtEllen1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        lblBerichten = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punten van spelers bijhouden in propertybestand");

        jLabel1.setText("Jan");

        fxtJan.setForeground(new java.awt.Color(0, 0, 255));
        fxtJan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtJan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fxtJan.setEnabled(false);
        fxtJan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setText("Piet");

        fxtPiet.setForeground(new java.awt.Color(0, 0, 255));
        fxtPiet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtPiet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fxtPiet.setEnabled(false);
        fxtPiet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setText("Karen");

        fxtKaren.setForeground(new java.awt.Color(0, 0, 255));
        fxtKaren.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtKaren.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fxtKaren.setEnabled(false);
        fxtKaren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setText("Ellen");

        fxtEllen.setForeground(new java.awt.Color(0, 0, 255));
        fxtEllen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtEllen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fxtEllen.setEnabled(false);
        fxtEllen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("basis/opgaven/Bundle"); // NOI18N
        btnOpslaan.setText(bundle.getString("btn.save")); // NOI18N
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        fxtJan1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtJan1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fxtPiet1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtPiet1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fxtKaren1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtKaren1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fxtEllen1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        fxtEllen1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(bundle.getString("label.titel")); // NOI18N

        lblBerichten.setForeground(new java.awt.Color(255, 0, 51));
        lblBerichten.setText("Hier komen eventuele berichten");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBerichten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fxtEllen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fxtJan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fxtPiet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fxtKaren, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fxtJan1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fxtPiet1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fxtKaren1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fxtEllen1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnOpslaan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fxtJan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(fxtPiet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(fxtKaren1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(fxtEllen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fxtJan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fxtPiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fxtKaren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fxtEllen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpslaan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBerichten)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        /**
         * tel de huidige punten bij de vorige en bewaar opnieuw in het bestand
         */
        Number piet = (Number) fxtPiet.getValue();
        Number piet1 = (Number) fxtPiet1.getValue();
        //Numbers can get only intValue the integer
        int somPiet = piet.intValue() + piet1.intValue();
        puntenStand.setProperty("Piet", String.valueOf(somPiet));
        
        int somJan = ((Number) fxtJan.getValue()).intValue()+((Number) fxtJan1.getValue()).intValue();
        puntenStand.setProperty("Jan", String.valueOf(somJan));
        
        int somEllen = ((Number) fxtEllen.getValue()).intValue()+((Number) fxtEllen1.getValue()).intValue();
        puntenStand.setProperty("Ellen", String.valueOf(somEllen));
        
        int somKaren = ((Number) fxtKaren.getValue()).intValue()+((Number) fxtKaren1.getValue()).intValue();
        puntenStand.setProperty("Karen", String.valueOf(somKaren));
        
            
        try (FileWriter writer = new FileWriter(sourceBestand)) {
            puntenStand.store(writer, "Park-gent punten");
            

        } catch (Exception ex) {
            System.out.println("Opslaan van de  punten faalt voor locatie: " + locatiePuntenBestand);
            ex.printStackTrace(System.err);
        }


    }//GEN-LAST:event_btnOpslaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_PuntenBijhouden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_PuntenBijhouden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_PuntenBijhouden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_PuntenBijhouden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _PuntenBijhouden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JFormattedTextField fxtEllen;
    private javax.swing.JFormattedTextField fxtEllen1;
    private javax.swing.JFormattedTextField fxtJan;
    private javax.swing.JFormattedTextField fxtJan1;
    private javax.swing.JFormattedTextField fxtKaren;
    private javax.swing.JFormattedTextField fxtKaren1;
    private javax.swing.JFormattedTextField fxtPiet;
    private javax.swing.JFormattedTextField fxtPiet1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBerichten;
    // End of variables declaration//GEN-END:variables
}
